// Copyright 2018 Google LLC
//
// Use of this source code is governed by an MIT-style
// license that can be found in the LICENSE file or at
// https://opensource.org/licenses/MIT.

use clap::Parser;
use service::{WorldClient, init_tracing, sudoku::{SudokuSize, Sudoku}};
use std::{net::SocketAddr, time::Duration};
use tarpc::{client, context, tokio_serde::formats::Json};
use tokio::time::sleep;
use tracing::Instrument;

#[derive(Parser)]
struct Flags {
    /// Sets the server address to connect to.
    #[clap(long)]
    server_addr: SocketAddr,
    /// Sets the name to say hello to.
    #[clap(long)]
    name: String,

    #[clap(long)]
    size: SudokuSize
}

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let flags = Flags::parse();
    let tracer_provider = init_tracing("Tarpc Example Client")?;

    let mut transport = tarpc::serde_transport::tcp::connect(flags.server_addr, Json::default);
    transport.config_mut().max_frame_length(usize::MAX);

    // WorldClient is generated by the service attribute. It has a constructor `new` that takes a
    // config and any Transport as input.
    let client = WorldClient::new(client::Config::default(), transport.await?).spawn();


    let hello = client.hello(context::current(), format!("{}", flags.name))
    .instrument(tracing::info_span!("Two Hellos"))
    .await;

    println!("respuesta: {:?}", hello);

    match hello {
        Ok(hello) => tracing::info!("{hello:?}"),
        Err(e) => tracing::warn!("{:?}", anyhow::Error::from(e)),
    }

    let sudoku = client.sudoku(context::current(), flags.size).await?;
    sudoku.unwrap().board.iter().for_each(|e| println!("{e:?}"));

    // Let the background span processor finish.
    sleep(Duration::from_micros(1)).await;
    tracer_provider.shutdown()?;

    Ok(())
}